In [1]:
import numpy as np

# NumPy funksiyalariga kirish

In [3]:
ls=[1,2,3,4,5,6,7]
np.array(ls)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
ls1=[[1,2,3],
    [4,5,6],
    [7,8,9]]
np.array(ls1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.random.random((3,3))

array([[0.15804466, 0.7953323 , 0.33822734],
       [0.76829449, 0.25384006, 0.18108703],
       [0.3861653 , 0.19614804, 0.80605598]])

In [8]:
np.arange(-10,10,2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [9]:
ar = np.array([[1,2],[3,4],[5,6]])
ar.flatten()

array([1, 2, 3, 4, 5, 6])

In [12]:
ar = np.array([[1,2],[3,4],[5,6]])
ar.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.array([1.23,5.7,2.38]).dtype


dtype('float64')

In [14]:
np.array([True,False,42,5.78]).dtype

dtype('float64')